#!/bin/bash
cp ../0x02-functions_nested_loops/{3-islower.c,4-isalpha.c,6-abs.c} .
cp ../0x04-more_functions_nested_loops/{0-isupper.c,1-isdigit.c} .
cp ../0x05-pointers_arrays_strings/{2-strlen.c,3-puts.c,9-strcpy.c} .
cp ../0x06-pointers_arrays_strings/{0-strcat.c,1-strncat.c,2-strncpy.c,3-strcmp.c} .
cp ../0x07-pointers_arrays_strings/{0-memset.c,1-memcpy.c,2-strchr.c,3-strspn.c,4-strpbrk.c,5-strstr.c} .
